a = 21;
b = 14;
c = 13
d = 17
e = input ( "write the valueof e\n" );
e = input ( "write the value of f\n");
e = input ( "write the value of g\n");
e = input ( "write the value of h\n");
w = a + e;
x = b - e;
y = c * e;
z = d / e;
fprintf( "%d + %d = %d\n", a,e,w );
fprintf ( "%d - %d = %d\n", b,e,x );
fprintf ( "%d * %d = %d\n", c,e,y );
fprintf ( "%d / %d = %d\n", d,e,z );